blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    path('blog', views.PostList.as_view(), name='post_list'),
    path('draft', views.DraftPostList.as_view(), name='draft_list'),
    path('about', views.AboutView.as_view(), name='about'),
    path('blog/<slug:slug>', views.PostDetails.as_view(), name='post_details'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('translator/', include('translator.urls', namespace='translator'))
]

translator/urls.py
from django.urls import path
from . import views

app_name = "translator"

urlpatterns = [
    path('', views.translator_view, name='translator')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = ((0, "Draft"), (1, "Publish"))


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return self.title

translator/models.py
from django.db import models

# Create your models here.

blog/views.py
from .models import Post
from django.views import generic


class HomePage(generic.TemplateView):
    template_name = "homepage.html"


class AboutView(generic.TemplateView):
    template_name = "about.html"


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-date_created')
    template_name = "post_list.html"


class PostDetails(generic.DetailView):
    model = Post
    template_name = "post_details.html"


class DraftPostList(generic.ListView):
    queryset = Post.objects.filter(status=0).order_by('-date_created')
    template_name = "posts_draft_list.html"

translator/views.py
from django.shortcuts import render
from . import translate


def translator_view(request):
    if request.method == 'POST':
        orig_text = request.POST['my_textarea']
        output = translate.translator(orig_text)
        context = {
            'orig_text': orig_text,
            'output': output
        }
        return render(request, 'translator.html', context)
    else:
        return render(request, 'translator.html')

blog/templates/about.html
{% extends "base.html" %}

{%block title%} About {%endblock%}

{%block content%}
 <h1 style="text-align:center"> About us</h1>
{%endblock%}

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%} {%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body>
    <div class="card text-center">
        <nav class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'translator:translator' %}">Translator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:about' %}">About us</a>
                </li>

            </ul>
        </nav>
    </div>
{%block content%}
{%endblock%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

blog/templates/homepage.html
{% extends "base.html" %}

{%block title%} Homepage {%endblock%}

{%block content%}
    <h1 style="text-align: center">There is a homepage</h1>
{%endblock%}

blog/templates/post_details.html
{% extends "base.html" %}

{%block title%} {{object.title}} {%endblock%}

{%block content%}
    <h1>{{object.title}}</h1>
    <p>{{object.content}}</p>
    <p>Author: {{object.author}}</p>
    <h6>{{object.date_created}}</h6>
{%endblock%}

blog/templates/post_list.html
{% extends "base.html" %}

{%block title%} Posts {%endblock%}

{%block content%}
    <div class="container">
        {%for post in post_list%}
        <div class="card m-3">
            <div class="card-body">
                <h1 class="card-title">{{post.title}}</h1>
                <p class="card-text">{{post.content | slice:"100"}}</p>
                <p class="card-text">Author: {{post.author | title}}</p>
                <a href="{% url 'blog:post_details' post.slug %}" class="btn btn-primary">Read more</a>
            </div>
        </div>
        {%endfor%}
    </div>
{%endblock%}

translator/templates/translator.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form action="{% url 'translator:translator' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-6 mt-3 left">
                <textarea class="form-control" rows="3" name="my_textarea">{{orig_text}}</textarea>
            </div>
            <div class="col-sm-6 mt-3 left">
                <textarea class="form-control" rows="3">{{output}}</textarea>
                <input class="btn btn-primary ml-3 mt-3" type="submit" value="Submit">
            </div>
        </div>
    </form>
</div>
{% endblock content %}